pipeline {
    agent any
    environment {
        PROJECT_DIR = 'src/FullstackApp'
        PROJECT = 'FullstackApp.csproj'
        CONFIGURATION = 'Release'
        PUBLISH_DIR = 'publish'
        ARTIFACT = "FullstackApp-${BUILD_NUMBER}.zip"
        NEXUS_DNS = ''
        IMAGE_NAME = "dotnet-image"
        IMAGE_TAG = "v${BUILD_NUMBER}"
        PORT = "5000"
    }

    stages {
        stage('Fetch code') {
            steps {
                git branch: 'Michael-stg', url: 'https://github.com/darisjerez/devops-class-dontnet-fullstack.git'
            }
        }

        stage('Restore') {
            steps {
                dir("${PROJECT_DIR}") {
                    sh "dotnet restore ${PROJECT}"
                }
            }
        }

        stage('Static Analysis / lint') {
            steps {
                dir("${PROJECT_DIR}") {
                    sh "dotnet format --verify-no-changes"
                }
            }
        }

        stage('Test and Code Coverage') {
            steps {
                dir("tests/FullstackApp.Tests") {
                    sh "dotnet test --collect:'XPlat Code Coverage' --verbosity normal"
                }
            } 
            post{
                always {
                    archiveArtifacts artifacts: "tests/FullstackApp.Tests/TestResults/**/*.cobertura.xml", allowEmptyArchive: true
                }
            }
        }

        stage('Build') {
            steps {
                dir("${PROJECT_DIR}") {
                    sh "dotnet build ${PROJECT} -c ${CONFIGURATION} --no-restore"
                }
            }
        }

        stage('Publish') {
            steps {
                dir("${PROJECT_DIR}") {
                    sh """
                    dotnet publish ${PROJECT} -c ${CONFIGURATION} -o ${PUBLISH_DIR} --no-build
                    zip -r ${ARTIFACT} ${PUBLISH_DIR}
                    """
                }
            }
        }
        stage('Build Image') {
            steps {
                script{

                    docker.build("${IMAGE_NAME}:${IMAGE_TAG}", ".")
                }
            }
        }

        stage('Run Container') {
            steps {
                script{
                    sh """
                    docker run -d -p ${PORT}:5000 ${IMAGE_NAME}:${IMAGE_TAG}

                    """
                }
            }
        }

        stage('Upload Nexus Artifact') {
            steps {
                script {
                    nexusArtifactUploader(
                        nexusVersion: 'nexus3',
                        protocol: 'http',
                        nexusUrl: "${NEXUS_DNS}",
                        groupId: 'com.babel.dotnet',
                        version: "${BUILD_NUMBER}",
                        repository: 'dotnet-releases',
                        credentialsId: 'nexuslogin',
                        artifacts: [[
                            artifactId: 'FullstackApp',
                            classifier: '',
                            file: "${PROJECT_DIR}/${ARTIFACT}",
                            type: 'zip'
                        ]]
                    )
                }
            }
        }
    }
}
